CREATE OR REPLACE TRIGGER DATESTAGETRIGGER
AFTER INSERT ON DATESTAGE FOR EACH ROW
DECLARE
DATESTAGECOUNT INTEGER;
MATCHINGDATESTAGECOUNT INTEGER;
BEGIN
    SELECT COUNT(*) INTO MATCHINGDATESTAGECOUNT FROM DATEDIMENSION
    WHERE date_sk = :NEW.date_sk;
    IF(MATCHINGDATESTAGECOUNT = 0) THEN
        INSERT INTO DATEDIMENSION VALUES(:NEW.date_sk, :NEW.day, :NEW.month, :NEW.year,
        :NEW.week, :NEW.quarter,:NEW.dayofweek);
        --COMMIT;
    END IF;
END;