CREATE OR REPLACE TRIGGER PLAYERSTAGERTRIGGER
AFTER INSERT ON PLAYERSTAGE FOR EACH ROW
DECLARE 
PLAYERCOUNT INTEGER;
BEGIN
    SELECT COUNT(*) INTO PLAYERCOUNT FROM PLAYERDIM
    WHERE player_sk = :NEW.p_skey;
    IF(PLAYERCOUNT = 0)THEN
        INSERT INTO PLAYERDIM VALUES (:NEW.p_skey, 
        TRIM(:NEW.p_name)||' '||TRIM(:NEW.p_sname));
        --COMMIT;
    END IF;    
END;