CREATE OR REPLACE TRIGGER TEAMSTAGETRIGGER
AFTER INSERT ON TEAMSTAGE FOR EACH ROW
DECLARE 
TEAMSTAGECOUNT NUMBER(38,19);
BEGIN
    SELECT COUNT(*) INTO TEAMSTAGECOUNT FROM TEAMDIM
    WHERE team_sk = :NEW.Team_skey;
    IF(TEAMSTAGECOUNT = 0)THEN
        INSERT INTO TEAMDIM VALUES (:NEW.Team_skey,:NEW.Team_name);
        --COMMIT;
    END IF;    
END;