CREATE OR REPLACE TRIGGER TOURNAMENTSTAGETRIGGER
AFTER INSERT ON TOURNAMENTSTAGE FOR EACH ROW
DECLARE 
TOURNAMENTDATACOUNT NUMBER(38,2);
BEGIN
    SELECT COUNT(*) INTO TOURNAMENTDATACOUNT FROM TOURNAMENTDIM
    WHERE tournament_sk = :NEW.t_skey;
    IF(TOURNAMENTDATACOUNT = 0) THEN 
        INSERT INTO TOURNAMENTDIM VALUES 
        (:NEW.t_skey,:NEW.t_descriprion,:NEW.Total_price);
        --COMMIT;
    END IF;    
END;